[package]
name = "s2p"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
darling = "0.20.1"
quote = "1.0.27"
syn = "2.0.16"

[dev-dependencies]
polars = "0.30.0"
